name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: yarn install

      - name: Build do projeto
        run: yarn build

      - name: Configurar usuário do Git
        run: |
          git config --global user.email "alexandrebsilva9@gmail.com"
          git config --global user.name "alexandre-silvaa"

      - name: Deploy para o GitHub Pages
        run: npx gh-pages -d dist
